// ROOT
export const IS_LOADING = 'IS_LOADING';

// NOTIFICATIONS
export const SHOW_NOTIFICATION = 'SHOW_NOTIFICATION';
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION';

// USERS
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';

// LEDGER
export const SET_TRANSACTIONS_LIST = 'SET_TRANSACTIONS_LIST';
export const SET_FROM_TRANSACTION = 'SET_FROM_TRANSACTION';
export const SET_TO_TRANSACTION = 'SET_TO_TRANSACTION';

// SCHEMAS
export const SET_SCHEMA_LIST = 'SET_SCHEMA_LIST';
export const SET_SCHEMA_DETAILS = 'SET_SCHEMA_DETAILS';
export const SET_PARENT_SCHEMA_DETAILS = 'SET_PARENT_SCHEMA_DETAILS';
export const SET_ATTRIBUTE_TYPES = 'SET_ATTRIBUTE_TYPES';

// PROOF_TEMPLATES
export const SET_PROOF_TEMPLATE_LIST = 'SET_PROOF_TEMPLATE_LIST';
export const SET_PROOF_TEMPLATE_DETAILS = 'SET_PROOF_TEMPLATE_DETAILS';

// WALLETS & CONNECTIONS
export const SET_WALLET_INFO = 'SET_WALLET_INFO';
